In [85]:
import pandas as pd

from pprint import pprint

data = pd.read_json('purchase_data.json')
print(data.head())

   Age Gender  Item ID                                  Item Name  Price  \
0   38   Male      165                Bone Crushing Silver Skewer   3.37
1   21   Male      119  Stormbringer, Dark Blade of Ending Misery   2.32
2   34   Male      174                            Primitive Blade   2.46
3   21   Male       92                               Final Critic   1.36
4   23   Male       63                             Stormfury Mace   1.27

             SN
0     Aelalis34
1        Eolo46
2   Assastnya25
3  Pheusrical25
4        Aela59

In [90]:
# Number of players
unique_players = len(data["SN"].unique())
print("Total number of players:", unique_players)

Total number of players: 573

<h1>Purchasing Analysis (Total) </h1>

In [91]:

# * Number of Unique Items
unique_items = len(data['Item ID'].unique())
print("Number of Unique Items:", unique_items)

# * Average Purchase Price
avg_price = round(data["Price"].mean(), 2)
print("Average Purchase Price $", avg_price, sep="")

# * Total Number of Purchases
total_purchases = len(data)
print("Total Purchases:", total_purchases)

# * Total Revenue
total_revenue = round(data["Price"].sum(), 2)
print("Total Revenue: $", total_revenue, sep="")

Number of Unique Items: 183
Average Purchase Price $2.93
Total Purchases: 780
Total Revenue: $2286.33

<h1> **Gender Demographics** </h1>

In [133]:

# Removing duplicate players from the data
data_without_duplicate_players = data.drop_duplicates(subset=["SN"])

# Seperating the no duplicate data into gender groups
gender_groups = data_without_duplicate_players["Gender"].value_counts()

# Printing Percentage of palyers and total count according to their gender
x = pd.DataFrame({"Total Count":gender_groups,
                   "Percentage of Players": round(gender_groups/unique_players * 100, 2)})
print(x)

                       Percentage of Players  Total Count
Male                                   81.15          465
Female                                 17.45          100
Other / Non-Disclosed                   1.40            8

<h1> **Purchasing Analysis (Gender)** </h1>

In [142]:
# Number of purchases by each gender
grouped_data = data.groupby(["Gender"])
for x, y in grouped_data:
    price_column = y["Price"]
    print(x)
    print("Total Purchases By:", len(y))
    print("Average Purchase Price: $", round(price_column.mean(), 2), sep="")
    print("Total Purchase Value: $", round(price_column.sum(), 2), sep="")
#   TODO : Figure out how to calculate Normalized Totals
    print("**************************")
#   * Normalized Totals

Female
Total Purchases By: 136
Average Purchase Price: $2.82
Total Purchase Value: $382.91
**************************
Male
Total Purchases By: 633
Average Purchase Price: $2.95
Total Purchase Value: $1867.68
**************************
Other / Non-Disclosed
Total Purchases By: 11
Average Purchase Price: $3.25
Total Purchase Value: $35.74
**************************

<h1>**Age Demographics**</h1>

In [141]:
grouped_data = data.groupby(["Age"])
for x, y in grouped_data:
    price_column = y["Price"]
    print(x)
    print("Total Purchases By:", len(y))
    print("Average Purchase Price: $", round(price_column.mean(), 2), sep="")
    print("Total Purchase Value: $", round(price_column.sum(), 2), sep="")
#   TODO : Figure out how to calculate Normalized Totals
    print("**************************")

7
Total Purchases By: 19
Average Purchase Price: $2.92
Total Purchase Value: $55.47
**************************
8
Total Purchases By: 3
Average Purchase Price: $1.96
Total Purchase Value: $5.87
**************************
9
Total Purchases By: 6
Average Purchase Price: $3.69
Total Purchase Value: $22.12
**************************
10
Total Purchases By: 4
Average Purchase Price: $3.29
Total Purchase Value: $13.16
**************************
11
Total Purchases By: 9
Average Purchase Price: $2.97
Total Purchase Value: $26.76
**************************
12
Total Purchases By: 5
Average Purchase Price: $3.84
Total Purchase Value: $19.21
**************************
13
Total Purchases By: 11
Average Purchase Price: $2.14
Total Purchase Value: $23.52
**************************
14
Total Purchases By: 6
Average Purchase Price: $2.38
Total Purchase Value: $14.3
**************************
15
Total Purchases By: 47
Average Purchase Price: $2.99
Total Purchase Value: $140.36
**************************
16
Total Purchases By: 23
Average Purchase Price: $2.64
Total Purchase Value: $60.71
**************************
17
Total Purchases By: 17
Average Purchase Price: $3.01
Total Purchase Value: $51.11
**************************
18
Total Purchases By: 24
Average Purchase Price: $2.8
Total Purchase Value: $67.14
**************************
19
Total Purchases By: 22
Average Purchase Price: $3.05
Total Purchase Value: $67.1
**************************
20
Total Purchases By: 98
Average Purchase Price: $2.88
Total Purchase Value: $282.68
**************************
21
Total Purchases By: 43
Average Purchase Price: $2.8
Total Purchase Value: $120.37
**************************
22
Total Purchases By: 68
Average Purchase Price: $3.03
Total Purchase Value: $206.05
**************************
23
Total Purchases By: 57
Average Purchase Price: $2.74
Total Purchase Value: $156.21
**************************
24
Total Purchases By: 70
Average Purchase Price: $3.05
Total Purchase Value: $213.46
**************************
25
Total Purchases By: 67
Average Purchase Price: $3.08
Total Purchase Value: $206.52
**************************
26
Total Purchases By: 13
Average Purchase Price: $2.45
Total Purchase Value: $31.83
**************************
27
Total Purchases By: 19
Average Purchase Price: $3.06
Total Purchase Value: $58.21
**************************
28
Total Purchases By: 5
Average Purchase Price: $2.56
Total Purchase Value: $12.81
**************************
29
Total Purchases By: 21
Average Purchase Price: $2.9
Total Purchase Value: $60.96
**************************
30
Total Purchases By: 18
Average Purchase Price: $3.11
Total Purchase Value: $56.01
**************************
31
Total Purchases By: 16
Average Purchase Price: $2.98
Total Purchase Value: $47.62
**************************
32
Total Purchases By: 11
Average Purchase Price: $3.41
Total Purchase Value: $37.5
**************************
33
Total Purchases By: 11
Average Purchase Price: $2.89
Total Purchase Value: $31.8
**************************
34
Total Purchases By: 8
Average Purchase Price: $3.04
Total Purchase Value: $24.32
**************************
35
Total Purchases By: 12
Average Purchase Price: $3.08
Total Purchase Value: $37.02
**************************
36
Total Purchases By: 7
Average Purchase Price: $2.88
Total Purchase Value: $20.14
**************************
37
Total Purchases By: 9
Average Purchase Price: $2.35
Total Purchase Value: $21.11
**************************
38
Total Purchases By: 9
Average Purchase Price: $2.87
Total Purchase Value: $25.79
**************************
39
Total Purchases By: 5
Average Purchase Price: $3.07
Total Purchase Value: $15.34
**************************
40
Total Purchases By: 14
Average Purchase Price: $3.22
Total Purchase Value: $45.11
**************************
42
Total Purchases By: 1
Average Purchase Price: $2.11
Total Purchase Value: $2.11
**************************
43
Total Purchases By: 1
Average Purchase Price: $3.81
Total Purchase Value: $3.81
**************************
45
Total Purchases By: 1
Average Purchase Price: $2.72
Total Purchase Value: $2.72
**************************

<h1>**Top Spenders**</h1>

In [180]:
# * Identify the the top 5 spenders in the game by total purchase value, then list (in a table):
grouped_data = data.groupby(["SN"])
# print(grouped_data["Price"].sum().nlargest(n=5))

temp_df = pd.DataFrame([])
for x, y in grouped_data:
    print(x)
    print("Total Spending:", y["Price"].sum())
    print("*********")

#   * SN
#   * Purchase Count
#   * Average Purchase Price
#   * Total Purchase Value

Adairialis76
Total Spending: 2.46
*********
Aduephos78
Total Spending: 6.699999999999999
*********
Aeduera68
Total Spending: 5.800000000000001
*********
Aela49
Total Spending: 2.46
*********
Aela59
Total Spending: 1.27
*********
Aelalis34
Total Spending: 5.0600000000000005
*********
Aelin32
Total Spending: 3.14
*********
Aeliriam77
Total Spending: 6.720000000000001
*********
Aeliriarin93
Total Spending: 2.04
*********
Aeliru63
Total Spending: 8.98
*********
Aellyria80
Total Spending: 4.32
*********
Aellyrialis39
Total Spending: 3.15
*********
Aellysup38
Total Spending: 3.61
*********
Aelollo59
Total Spending: 1.55
*********
Aenarap34
Total Spending: 1.65
*********
Aenasu69
Total Spending: 3.27
*********
Aeral43
Total Spending: 2.7199999999999998
*********
Aeral85
Total Spending: 4.25
*********
Aeral97
Total Spending: 2.35
*********
Aeri84
Total Spending: 6.6
*********
Aerillorin70
Total Spending: 1.88
*********
Aerithllora36
Total Spending: 10.45
*********
Aerithnucal56
Total Spending: 3.1799999999999997
*********
Aerithnuphos61
Total Spending: 1.69
*********
Aerithriaphos45
Total Spending: 2.38
*********
Aesty51
Total Spending: 1.82
*********
Aesur96
Total Spending: 4.66
*********
Aethe80
Total Spending: 2.32
*********
Aethedru70
Total Spending: 2.9699999999999998
*********
Aidain51
Total Spending: 6.84
*********
Aidaira26
Total Spending: 1.72
*********
Aidaira48
Total Spending: 1.73
*********
Aiduecal76
Total Spending: 2.33
*********
Aiduesu83
Total Spending: 2.63
*********
Ailaesuir66
Total Spending: 1.88
*********
Aillycal84
Total Spending: 4.0
*********
Aillyriadru65
Total Spending: 1.8399999999999999
*********
Aina42
Total Spending: 3.01
*********
Aina43
Total Spending: 2.46
*********
Airal46
Total Spending: 2.67
*********
Airi27
Total Spending: 7.57
*********
Airidil41
Total Spending: 3.59
*********
Airithrin43
Total Spending: 3.5700000000000003
*********
Aisur51
Total Spending: 1.49
*********
Aisurphos78
Total Spending: 3.73
*********
Aithelis62
Total Spending: 3.79
*********
Alaephos75
Total Spending: 6.63
*********
Alaesu77
Total Spending: 2.33
*********
Alaesu91
Total Spending: 1.03
*********
Alallo58
Total Spending: 4.14
*********
Alarap40
Total Spending: 2.7199999999999998
*********
Alim85
Total Spending: 3.61
*********
Alo67
Total Spending: 2.11
*********
Anallorgue57
Total Spending: 4.87
*********
Arithllorin55
Total Spending: 3.74
*********
Assassa38
Total Spending: 5.609999999999999
*********
Assassa43
Total Spending: 3.89
*********
Assassasda84
Total Spending: 3.89
*********
Assassasta79
Total Spending: 9.120000000000001
*********
Assastnya25
Total Spending: 4.75
*********
Assesi91
Total Spending: 1.73
*********
Assilsan72
Total Spending: 3.58
*********
Assistasda90
Total Spending: 4.15
*********
Assistast50
Total Spending: 3.55
*********
Assithasta65
Total Spending: 3.61
*********
Assosia38
Total Spending: 1.9300000000000002
*********
Assosiasta83
Total Spending: 2.8200000000000003
*********
Assossa43
Total Spending: 4.89
*********
Assylla81
Total Spending: 6.6000000000000005
*********
Astydil38
Total Spending: 3.21
*********
Asur53
Total Spending: 4.04
*********
Baelollodeu94
Total Spending: 2.77
*********
Bartassaya73
Total Spending: 3.91
*********
Billysu76
Total Spending: 2.86
*********
Chadadarya31
Total Spending: 1.82
*********
Chadanto83
Total Spending: 6.23
*********
Chadjask77
Total Spending: 10.01
*********
Chadossa56
Total Spending: 7.8500000000000005
*********
Chadossa89
Total Spending: 2.46
*********
Chamadar27
Total Spending: 4.23
*********
Chamadar61
Total Spending: 5.67
*********
Chamadar79
Total Spending: 4.3
*********
Chamadarnya73
Total Spending: 4.3
*********
Chamadarsda63
Total Spending: 2.46
*********
Chamastya76
Total Spending: 3.7
*********
Chamilsala65
Total Spending: 5.52
*********
Chamilsan75
Total Spending: 5.64
*********
Chamim85
Total Spending: 4.12
*********
Chamimla73
Total Spending: 3.27
*********
Chamirra53
Total Spending: 1.28
*********
Chamirrasya33
Total Spending: 1.11
*********
Chamirraya83
Total Spending: 4.83
*********
Chamistast30
Total Spending: 4.49
*********
Chamjasknya65
Total Spending: 3.8
*********
Chamosia29
Total Spending: 6.16
*********
Chamucosda93
Total Spending: 3.56
*********
Chanadar44
Total Spending: 7.1899999999999995
*********
Chanassa48
Total Spending: 1.3900000000000001
*********
Chanastnya43
Total Spending: 1.3599999999999999
*********
Chanastsda67
Total Spending: 8.96
*********
Chanastst38
Total Spending: 6.42
*********
Chanirra56
Total Spending: 1.5
*********
Chanirra79
Total Spending: 2.9699999999999998
*********
Chanirrala39
Total Spending: 5.5600000000000005
*********
Chanirrasta87
Total Spending: 3.3600000000000003
*********
Chanjask65
Total Spending: 3.3899999999999997
*********
Chanjaskan37
Total Spending: 3.14
*********
Chanjaskan89
Total Spending: 2.91
*********
Chanosia60
Total Spending: 6.74
*********
Chanosia65
Total Spending: 2.36
*********
Chanosiast43
Total Spending: 5.92
*********
Chanosiaya39
Total Spending: 6.75
*********
Chanosseya79
Total Spending: 4.0
*********
Chrathybust28
Total Spending: 1.3599999999999999
*********
Cosadar58
Total Spending: 3.91
*********
Crausirra42
Total Spending: 3.29
*********
Deelilsasya30
Total Spending: 1.98
*********
Deural48
Total Spending: 7.27
*********
Dyally87
Total Spending: 4.51
*********
Ennoncil86
Total Spending: 1.9100000000000001
*********
Eoda93
Total Spending: 11.58
*********
Eodailis27
Total Spending: 3.55
*********
Eoduenurin62
Total Spending: 1.49
*********
Eollym91
Total Spending: 1.28
*********
Eolo46
Total Spending: 2.32
*********
Eoral49
Total Spending: 1.8399999999999999
*********
Eoralphos86
Total Spending: 4.25
*********
Eosrirgue62
Total Spending: 2.36
*********
Eosur70
Total Spending: 5.85
*********
Eosurdru76
Total Spending: 7.24
*********
Eosursurap97
Total Spending: 2.23
*********
Eothe56
Total Spending: 2.6
*********
Eratiel90
Total Spending: 2.29
*********
Ermol76
Total Spending: 1.79
*********
Erudrion71
Total Spending: 2.66
*********
Eryon48
Total Spending: 2.11
*********
Ethralan59
Total Spending: 1.85
*********
Ethralista69
Total Spending: 4.39
*********
Ethruard50
Total Spending: 5.699999999999999
*********
Ethrusuard41
Total Spending: 7.93
*********
Eudasu82
Total Spending: 3.51
*********
Eula35
Total Spending: 3.62
*********
Eulaeria40
Total Spending: 3.73
*********
Eulidru49
Total Spending: 3.33
*********
Euliria52
Total Spending: 2.04
*********
Eullydru35
Total Spending: 2.35
*********
Euna48
Total Spending: 4.25
*********
Eural50
Total Spending: 7.68
*********
Eurallo89
Total Spending: 5.6
*********
Eurinu48
Total Spending: 3.25
*********
Eurisuru25
Total Spending: 8.29
*********
Eurith26
Total Spending: 4.37
*********
Eusri26
Total Spending: 2.91
*********
Eusri44
Total Spending: 2.55
*********
Eusri70
Total Spending: 10.55
*********
Eustyria89
Total Spending: 4.75
*********
Eusur90
Total Spending: 6.0600000000000005
*********
Eyircil84
Total Spending: 1.06
*********
Faralcil63
Total Spending: 3.27
*********
Farenon57
Total Spending: 6.640000000000001
*********
Farusrian86
Total Spending: 6.8100000000000005
*********
Filon68
Total Spending: 2.34
*********
Filrion44
Total Spending: 6.11
*********
Filrion59
Total Spending: 2.07
*********
Fironon91
Total Spending: 2.46
*********
Frichadar89
Total Spending: 4.23
*********
Frichassala85
Total Spending: 2.85
*********
Frichast72
Total Spending: 2.2
*********
Frichaststa61
Total Spending: 4.95
*********
Frichaya88
Total Spending: 9.16
*********
Frichilsasya78
Total Spending: 3.74
*********
Frichim27
Total Spending: 4.5600000000000005
*********
Frichim77
Total Spending: 3.96
*********
Frichistast39
Total Spending: 3.56
*********
Frichistasta59
Total Spending: 4.17
*********
Frichjask31
Total Spending: 2.17
*********
Frichjaskan98
Total Spending: 3.68
*********
Frichosiala98
Total Spending: 8.940000000000001
*********
Frichossast75
Total Spending: 3.61
*********
Frichossast86
Total Spending: 3.62
*********
Haedasu65
Total Spending: 8.49
*********
Haellysu29
Total Spending: 12.73
*********
Haerith37
Total Spending: 10.14
*********
Haerithp41
Total Spending: 3.2
*********
Hailaphos89
Total Spending: 5.87
*********
Hainaria90
Total Spending: 3.39
*********
Hala31
Total Spending: 1.72
*********
Hallysucal81
Total Spending: 1.5899999999999999
*********
Heolo60
Total Spending: 1.24
*********
Heosrisuir72
Total Spending: 4.82
*********
Heosurnuru52
Total Spending: 1.73
*********
Heuli25
Total Spending: 3.48
*********
Heunadil74
Total Spending: 3.8200000000000003
*********
Heuralsti66
Total Spending: 4.75
*********
Hiadanurin36
Total Spending: 3.96
*********
Hiarideu73
Total Spending: 2.23
*********
Hiasri33
Total Spending: 2.2800000000000002
*********
Hiasur92
Total Spending: 4.87
*********
Hilaerin92
Total Spending: 6.87
*********
Hiral75
Total Spending: 1.45
*********
Hirirap39
Total Spending: 2.33
*********
Iadueria43
Total Spending: 4.5
*********
Ialallo29
Total Spending: 3.15
*********
Ialidru40
Total Spending: 1.24
*********
Ialistidru50
Total Spending: 7.34
*********
Iallyphos37
Total Spending: 2.34
*********
Ialo60
Total Spending: 4.08
*********
Iaralrgue74
Total Spending: 6.36
*********
Iaralsuir44
Total Spending: 3.73
*********
Iarilis73
Total Spending: 1.9300000000000002
*********
Iarithdil76
Total Spending: 3.81
*********
Iasur80
Total Spending: 4.87
*********
Iathenudil29
Total Spending: 4.88
*********
Idai61
Total Spending: 3.6
*********
Idairin80
Total Spending: 4.3
*********
Idaria87
Total Spending: 4.87
*********
Iduedru67
Total Spending: 3.32
*********
Ila44
Total Spending: 7.84
*********
Iladarla40
Total Spending: 3.91
*********
Ilaesudil92
Total Spending: 2.2800000000000002
*********
Ilariarin45
Total Spending: 4.23
*********
Ilassa51
Total Spending: 2.21
*********
Ilast79
Total Spending: 1.2
*********
Ilaststa70
Total Spending: 1.27
*********
Iliel92
Total Spending: 3.7
*********
Ililsa62
Total Spending: 7.4
*********
Ililsan66
Total Spending: 1.03
*********
Ilimya66
Total Spending: 3.48
*********
Ilirrasda54
Total Spending: 3.61
*********
Ilogha82
Total Spending: 8.61
*********
Ilophos58
Total Spending: 4.87
*********
Ilosia37
Total Spending: 1.48
*********
Ilosu82
Total Spending: 2.8200000000000003
*********
Ilrian97
Total Spending: 1.24
*********
Ina92
Total Spending: 4.54
*********
Indcil77
Total Spending: 8.530000000000001
*********
Indirrian56
Total Spending: 2.46
*********
Indonmol95
Total Spending: 2.29
*********
Ingatcil75
Total Spending: 8.44
*********
Ingonon91
Total Spending: 2.88
*********
Inguard95
Total Spending: 3.96
*********
Inguron55
Total Spending: 2.23
*********
Iral74
Total Spending: 3.58
*********
Iri67
Total Spending: 4.0
*********
Irillo49
Total Spending: 4.32
*********
Irith83
Total Spending: 2.33
*********
Irithrap69
Total Spending: 4.75
*********
Iskadarya95
Total Spending: 8.79
*********
Iskassa50
Total Spending: 1.79
*********
Isketo41
Total Spending: 1.32
*********
Iskichinya81
Total Spending: 4.67
*********
Iskimnya76
Total Spending: 5.82
*********
Iskirra45
Total Spending: 2.29
*********
Iskista88
Total Spending: 5.07
*********
Iskista96
Total Spending: 4.83
*********
Iskistasda86
Total Spending: 4.14
*********
Iskjaskan81
Total Spending: 2.38
*********
Iskjaskst81
Total Spending: 3.71
*********
Iskosia51
Total Spending: 6.699999999999999
*********
Iskosian40
Total Spending: 3.39
*********
Iskossa88
Total Spending: 5.449999999999999
*********
Iskossan49
Total Spending: 6.180000000000001
*********
Iskossasda43
Total Spending: 2.41
*********
Iskossaya95
Total Spending: 3.13
*********
Isri49
Total Spending: 1.9100000000000001
*********
Isri59
Total Spending: 3.74
*********
Isrirgue68
Total Spending: 4.36
*********
Isurria36
Total Spending: 11.010000000000002
*********
Isurriarap71
Total Spending: 4.16
*********
Isursti83
Total Spending: 11.05
*********
Ithergue48
Total Spending: 6.42
*********
Ithesuphos68
Total Spending: 2.7800000000000002
*********
Jeyciman68
Total Spending: 3.15
*********
Jiskassa76
Total Spending: 3.83
*********
Jiskilsa35
Total Spending: 3.81
*********
Jiskimsda56
Total Spending: 3.91
*********
Jiskirran77
Total Spending: 3.96
*********
Jiskjask80
Total Spending: 2.91
*********
Jiskosiala43
Total Spending: 3.66
*********
Jiskossa51
Total Spending: 8.14
*********
Koikirra25
Total Spending: 2.23
*********
Lamil70
Total Spending: 1.49
*********
Lamil79
Total Spending: 2.34
*********
Lamon28
Total Spending: 4.39
*********
Lamyon68
Total Spending: 1.55
*********
Lassadarsda57
Total Spending: 1.03
*********
Lassassasda30
Total Spending: 6.07
*********
Lassassast73
Total Spending: 5.109999999999999
*********
Lassast89
Total Spending: 6.78
*********
Lassilsa41
Total Spending: 4.42
*********
Lassilsa63
Total Spending: 1.27
*********
Lassilsala30
Total Spending: 3.21
*********
Lassimla92
Total Spending: 2.17
*********
Lassista97
Total Spending: 1.03
*********
Lassjask63
Total Spending: 4.8
*********
Lassjaskan73
Total Spending: 7.98
*********
Layjask75
Total Spending: 4.16
*********
Leulaesti78
Total Spending: 3.42
*********
Leyirra83
Total Spending: 4.45
*********
Liawista80
Total Spending: 3.27
*********
Liri91
Total Spending: 5.59
*********
Lirtassa47
Total Spending: 2.09
*********
Lirtast83
Total Spending: 3.55
*********
Lirtilsan89
Total Spending: 4.07
*********
Lirtista72
Total Spending: 4.36
*********
Lirtistanya48
Total Spending: 3.42
*********
Lirtistasta79
Total Spending: 3.76
*********
Lirtosia72
Total Spending: 8.37
*********
Lirtossa78
Total Spending: 3.58
*********
Lirtossa84
Total Spending: 4.62
*********
Lirtossan50
Total Spending: 3.51
*********
Lirtossanya27
Total Spending: 1.79
*********
Lirtyrdesta65
Total Spending: 1.8399999999999999
*********
Lisadar44
Total Spending: 2.31
*********
Lisasi93
Total Spending: 6.42
*********
Lisassa26
Total Spending: 4.25
*********
Lisassa39
Total Spending: 1.56
*********
Lisassa49
Total Spending: 2.11
*********
Lisassasta50
Total Spending: 6.59
*********
Lisico81
Total Spending: 1.5899999999999999
*********
Lisimsda29
Total Spending: 3.62
*********
Lisiriya82
Total Spending: 3.51
*********
Lisirra55
Total Spending: 5.79
*********
Lisirrast82
Total Spending: 1.5899999999999999
*********
Lisirraya76
Total Spending: 4.1
*********
Lisista27
Total Spending: 2.11
*********
Lisistasya93
Total Spending: 3.91
*********
Lisistaya47
Total Spending: 9.19
*********
Lisjaskan36
Total Spending: 7.68
*********
Lisjasksda68
Total Spending: 4.05
*********
Lisjaskya84
Total Spending: 3.11
*********
Lisosianya62
Total Spending: 1.55
*********
Lisosiast26
Total Spending: 6.74
*********
Lisossa25
Total Spending: 3.44
*********
Lisossa63
Total Spending: 5.92
*********
Lisossan98
Total Spending: 9.100000000000001
*********
Lisossanya98
Total Spending: 2.23
*********
Lisovynya38
Total Spending: 5.15
*********
Malista67
Total Spending: 3.01
*********
Malunil62
Total Spending: 8.89
*********
Marassanya92
Total Spending: 4.37
*********
Marassaya49
Total Spending: 2.7199999999999998
*********
Marilsa48
Total Spending: 4.75
*********
Marilsanya48
Total Spending: 4.16
*********
Marilsasya33
Total Spending: 2.07
*********
Marim28
Total Spending: 6.5600000000000005
*********
Marirrasta50
Total Spending: 6.22
*********
Marjasksda39
Total Spending: 2.19
*********
Marundi65
Total Spending: 4.07
*********
Meosridil82
Total Spending: 3.8200000000000003
*********
Mindadaran26
Total Spending: 2.7199999999999998
*********
Mindassast27
Total Spending: 2.07
*********
Mindetosya30
Total Spending: 2.31
*********
Mindilsa60
Total Spending: 6.37
*********
Mindimnya67
Total Spending: 12.739999999999998
*********
Mindirra92
Total Spending: 9.01
*********
Mindjasksya61
Total Spending: 3.89
*********
Mindosiasya28
Total Spending: 1.24
*********
Mindossa76
Total Spending: 1.03
*********
Mindossasya74
Total Spending: 2.17
*********
Minduli80
Total Spending: 4.62
*********
Narirra38
Total Spending: 8.42
*********
Nitherian58
Total Spending: 2.23
*********
Palatyon26
Total Spending: 3.47
*********
Palurrian69
Total Spending: 4.95
*********
Phadai31
Total Spending: 2.7800000000000002
*********
Phadue96
Total Spending: 3.15
*********
Phaedai25
Total Spending: 2.46
*********
Phaedan76
Total Spending: 1.8399999999999999
*********
Phaeduesurgue38
Total Spending: 4.23
*********
Phaestycal84
Total Spending: 3.62
*********
Phainasu47
Total Spending: 2.91
*********
Phairinum94
Total Spending: 4.0

*********
Phalinun47
Total Spending: 1.73
*********
Pharithdil38
Total Spending: 5.96
*********
Phenastya51
Total Spending: 4.75
*********
Pheodai94
Total Spending: 1.48
*********
Pheusrical25
Total Spending: 1.3599999999999999
*********
Phially37
Total Spending: 2.88
*********
Philistirap41
Total Spending: 1.69
*********
Philodil43
Total Spending: 1.49
*********
Phistym51
Total Spending: 3.79
*********
Phyali88
Total Spending: 2.29
*********
Qaronon57
Total Spending: 3.5700000000000003
*********
Qarrian82
Total Spending: 4.45
*********
Qarwen67
Total Spending: 9.969999999999999
*********
Qilanrion65
Total Spending: 2.98
*********
Qilatie51
Total Spending: 6.8100000000000005
*********
Qiluard68
Total Spending: 4.95
*********
Qilunan34
Total Spending: 2.32
*********
Quanenrian83
Total Spending: 3.79
*********
Quarunarn52
Total Spending: 4.75
*********
Quarusrion32
Total Spending: 2.83
*********
Quelatarn54
Total Spending: 4.33
*********
Quelaton80
Total Spending: 1.72
*********
Queusurra38
Total Spending: 5.4
*********
Quinarap53
Total Spending: 2.46
*********
Raedalis34
Total Spending: 2.55
*********
Raeduerin33
Total Spending: 1.24
*********
Raelly43
Total Spending: 3.37
*********
Raeri71
Total Spending: 1.5
*********
Raerithsti62
Total Spending: 6.77
*********
Raesty92
Total Spending: 5.46
*********
Raesurdil91
Total Spending: 3.81
*********
Raesursurap33
Total Spending: 5.199999999999999
*********
Raillydeu47
Total Spending: 6.02
*********
Raithe71
Total Spending: 3.61
*********
Ralaeriadeu65
Total Spending: 4.16
*********
Ralasti48
Total Spending: 4.14
*********
Ralonurin90
Total Spending: 3.96
*********
Rarith48
Total Spending: 1.03
*********
Rasrirgue43
Total Spending: 3.91
*********
Rathellorin54
Total Spending: 2.99
*********
Raysistast71
Total Spending: 4.51
*********
Reolacal36
Total Spending: 4.07
*********
Reula64
Total Spending: 7.57
*********
Reulae52
Total Spending: 4.07
*********
Reuthelis39
Total Spending: 3.87
*********
Rina82
Total Spending: 1.98
*********
Rinallorap73
Total Spending: 6.32
*********
Riralsti91
Total Spending: 4.67
*********
Ririp86
Total Spending: 3.71
*********
Ristydru66
Total Spending: 1.9100000000000001
*********
Rithe53
Total Spending: 1.3599999999999999
*********
Rithe77
Total Spending: 3.51
*********
Ryanara76
Total Spending: 7.0
*********
Ryastycal90
Total Spending: 1.21
*********
Saedaiphos46
Total Spending: 2.55
*********
Saedue76
Total Spending: 13.56
*********
Saelaephos52
Total Spending: 4.5600000000000005
*********
Saellyra72
Total Spending: 7.18
*********
Saelollop56
Total Spending: 3.68
*********
Saena74
Total Spending: 3.39
*********
Saerallora71
Total Spending: 2.36
*********
Saida58
Total Spending: 6.74
*********
Saidairiaphos61
Total Spending: 1.77
*********
Saisrilis27
Total Spending: 3.39
*********
Saistydru69
Total Spending: 4.12
*********
Saistyphos30
Total Spending: 5.98
*********
Salilis27
Total Spending: 1.56
*********
Sally64
Total Spending: 1.55
*********
Saralp86
Total Spending: 1.88
*********
Sausosia74
Total Spending: 5.59
*********
Seolollo93
Total Spending: 3.91
*********
Seorithstilis90
Total Spending: 8.39
*********
Seosri62
Total Spending: 5.529999999999999
*********
Seudaillorap38
Total Spending: 3.8200000000000003
*********
Seudanu38
Total Spending: 2.67
*********
Seuthelis34
Total Spending: 2.88
*********
Shaidanu32
Total Spending: 8.25
*********
Shidai42
Total Spending: 1.9300000000000002
*********
Sialaera37
Total Spending: 1.49
*********
Siarinum43
Total Spending: 2.38
*********
Siarithria38
Total Spending: 2.9699999999999998
*********
Siasri67
Total Spending: 1.2
*********
Siathecal92
Total Spending: 2.98
*********
Sida61
Total Spending: 6.34
*********
Sidap51
Total Spending: 2.07
*********
Silaera56
Total Spending: 1.72
*********
Silideu44
Total Spending: 1.77
*********
Silinu63
Total Spending: 3.11
*********
Sirira97
Total Spending: 4.15
*********
Smecherdi88
Total Spending: 3.96
*********
Sondadar26
Total Spending: 4.14
*********
Sondassa48
Total Spending: 2.67
*********
Sondassa68
Total Spending: 1.06
*********
Sondassasya91
Total Spending: 1.82
*********
Sondastan54
Total Spending: 10.24
*********
Sondenasta63
Total Spending: 2.77
*********
Sondilsa35
Total Spending: 3.58
*********
Sondilsa40
Total Spending: 3.8
*********
Sondim43
Total Spending: 9.379999999999999
*********
Sondim68
Total Spending: 4.62
*********
Sondim73
Total Spending: 3.5700000000000003
*********
Sondimla25
Total Spending: 2.17
*********
Sondossa55
Total Spending: 7.4399999999999995
*********
Sondossa91
Total Spending: 3.62
*********
Strairisti57
Total Spending: 2.21
*********
Streural92
Total Spending: 5.0600000000000005
*********
Strithenu87
Total Spending: 3.73
*********
Stryanastip77
Total Spending: 4.46
*********
Styaduen40
Total Spending: 3.91
*********
Sundadarla27
Total Spending: 4.3
*********
Sundassa93
Total Spending: 2.2
*********
Sundast29
Total Spending: 4.42
*********
Sundast87
Total Spending: 3.01
*********
Sundastnya66
Total Spending: 1.85
*********
Sundaststa26
Total Spending: 5.800000000000001
*********
Sundim98
Total Spending: 3.66
*********
Sundista85
Total Spending: 1.1400000000000001
*********
Sundjask71
Total Spending: 3.68
*********
Sundosiasta28
Total Spending: 3.39
*********
Sundossast30
Total Spending: 3.39
*********
Sweecossa42
Total Spending: 4.8100000000000005
*********
Syadaillo88
Total Spending: 3.5700000000000003
*********
Syally44
Total Spending: 2.22
*********
Syalollorap93
Total Spending: 4.51
*********
Syasriria69
Total Spending: 3.9800000000000004
*********
Syathe73
Total Spending: 4.89
*********
Taeduenu92
Total Spending: 4.39
*********
Tanimnya91
Total Spending: 1.73
*********
Tauldilsa43
Total Spending: 2.11
*********
Thourdirra92
Total Spending: 4.25
*********
Thryallym62
Total Spending: 5.0
*********
Tillyrin30
Total Spending: 9.190000000000001
*********
Tridaira71
Total Spending: 1.03
*********
Tyadaru49
Total Spending: 7.359999999999999
*********
Tyaelistidru84
Total Spending: 5.97
*********
Tyaelly53
Total Spending: 2.29
*********
Tyaelo67
Total Spending: 5.48
*********
Tyaelorgue39
Total Spending: 2.31
*********
Tyaenasti87
Total Spending: 1.96
*********
Tyaeristi78
Total Spending: 3.51
*********
Tyaerith73
Total Spending: 2.36
*********
Tyaili86
Total Spending: 1.28
*********
Tyalaesu89
Total Spending: 2.7800000000000002
*********
Tyananurgue44
Total Spending: 6.550000000000001
*********
Tyarithn67
Total Spending: 4.95
*********
Tyeosri53
Total Spending: 5.21
*********
Tyeosristi57
Total Spending: 3.8200000000000003
*********
Tyeuduen32
Total Spending: 1.49
*********
Tyeuduephos81
Total Spending: 3.15
*********
Tyeuladeu30
Total Spending: 4.82
*********
Tyeulisu40
Total Spending: 1.55
*********
Tyiaduenuru55
Total Spending: 1.69
*********
Tyida79
Total Spending: 3.56
*********
Tyidainu31
Total Spending: 2.86
*********
Tyidue95
Total Spending: 2.17
*********
Tyirithnu40
Total Spending: 5.61
*********
Tyisriphos58
Total Spending: 9.18
*********
Tyisur83
Total Spending: 4.51
*********
Tyithesura58
Total Spending: 2.6
*********
Umuard36
Total Spending: 3.55
*********
Undadar97
Total Spending: 3.91
*********
Undadarla37
Total Spending: 2.35
*********
Undare39
Total Spending: 2.46
*********
Undast38
Total Spending: 2.04
*********
Undirra73
Total Spending: 4.15
*********
Undirrala66
Total Spending: 17.06
*********
Undirrasta74
Total Spending: 1.16
*********
Undirrasta89
Total Spending: 2.2800000000000002
*********
Undistasta86
Total Spending: 3.02
*********
Undiwinya88
Total Spending: 2.77
*********
Undjaskla97
Total Spending: 4.57
*********
Undjasksya56
Total Spending: 4.53
*********
Undotesta33
Total Spending: 3.9
*********
Wailin72
Total Spending: 2.04
*********
Whaestysu86
Total Spending: 4.08
*********
Yadacal26
Total Spending: 1.9300000000000002
*********
Yadaisuir65
Total Spending: 8.56
*********
Yadanun74
Total Spending: 9.09
*********
Yalaeria91
Total Spending: 1.88
*********
Yaliru88
Total Spending: 3.71
*********
Yalo71
Total Spending: 2.41
*********
Yalostiphos68
Total Spending: 2.37
*********
Yaralnura48
Total Spending: 4.19
*********
Yararmol43
Total Spending: 1.55
*********
Yarirarn35
Total Spending: 2.88
*********
Yaristi64
Total Spending: 1.24
*********
Yarithllodeu72
Total Spending: 2.19
*********
Yarithphos28
Total Spending: 2.35
*********
Yarithsurgue62
Total Spending: 4.8100000000000005
*********
Yarmol79
Total Spending: 2.91
*********
Yarolwen77
Total Spending: 6.98
*********
Yasriphos60
Total Spending: 10.399999999999999
*********
Yasrisu92
Total Spending: 2.6
*********
Yasur35
Total Spending: 2.7800000000000002
*********
Yasur85
Total Spending: 2.04
*********
Yasurra52
Total Spending: 3.14
*********
Yathecal72
Total Spending: 7.77
*********
Yathecal82
Total Spending: 2.41
*********
Zhisrisu83
Total Spending: 2.46
*********
Zontibe81
Total Spending: 3.71
*********

In [181]:
# Identify the the top 5 spenders in the game by total purchase value, then list (in a table):
# SN
# Purchase Count
# Average Purchase Price
# Total Purchase Value
pur_data = data
#Group by screen name to find, total purchase per person, number of purchases per person, and average price price per person
purchase_amt_by_SN = pd.DataFrame(pur_data.groupby('SN')['Price'].sum())
num_purchase_by_SN = pd.DataFrame(pur_data.groupby('SN')['Price'].count())
avg_purchase_by_SN = pd.DataFrame(pur_data.groupby('SN')['Price'].mean())
# merge the above dfs
merged_top5 = pd.merge(purchase_amt_by_SN, num_purchase_by_SN, left_index = True, right_index = True).merge(avg_purchase_by_SN, left_index=True, right_index=True)
# rename columns
merged_top5.rename(columns = {'Price_x': 'Total Purchase Value', 'Price_y':'Purchase Count', 'Price':'Average Purchase Price'}, inplace = True)
# sort from highest purchase value to lowest
merged_top5.sort_values('Total Purchase Value', ascending = False, inplace=True)
# take top 5 only
merged_top5 = merged_top5.head()
# format
merged_top5.style.format({'Total Purchase Value': '${:.2f}', 'Average Purchase Price': '${:.2f}'})

In [182]:
# Identify the 5 most popular items by purchase count, then list (in a table):
# Item ID
# Item Name
# Purchase Count
# Item Price
# Total Purchase Value

# gets a count of each item by grouping by Item ID and counting the number of each IDs occurances
top5_items_ID = pd.DataFrame(pur_data.groupby('Item ID')['Item ID'].count())
#sort from high to low total purchase count
top5_items_ID.sort_values('Item ID', ascending = False, inplace = True)
#keep the first 6 rows because there is a tie
top5_items_ID = top5_items_ID.iloc[0:6][:]
#find the total purchase value of each item
top5_items_total = pd.DataFrame(pur_data.groupby('Item ID')['Price'].sum())
#merge purcahse count and total purcahse value 
top5_items = pd.merge(top5_items_ID, top5_items_total, left_index = True, right_index = True)
#drop duplicate items from original Df
no_dup_items = pur_data.drop_duplicates(['Item ID'], keep = 'last')
# merge to get all other info from the top 6 using the no dup df
top5_merge_ID = pd.merge(top5_items, no_dup_items, left_index = True, right_on = 'Item ID')
#keep only neede columns
top5_merge_ID = top5_merge_ID[['Item ID', 'Item Name', 'Item ID_x', 'Price_y', 'Price_x']]
#reset index as item ID for aesthetics
top5_merge_ID.set_index(['Item ID'], inplace = True)
# rename columns
top5_merge_ID.rename(columns =  {'Item ID_x': 'Purchase Count', 'Price_y': 'Item Price', 'Price_x': 'Total Purchase Value'}, inplace=True)
#format
top5_merge_ID.style.format({'Item Price': '${:.2f}', 'Total Purchase Value': '${:.2f}'})

In [183]:
# Most Profitable Items

# Identify the 5 most profitable items by total purchase value, then list (in a table):
# Item ID
# Item Name
# Purchase Count
# Item Price
# Total Purchase Value

# find total purcahse value and sort by high to low
top5_profit = pd.DataFrame(pur_data.groupby('Item ID')['Price'].sum())
top5_profit.sort_values('Price', ascending = False, inplace = True)
# only keep top 5
top5_profit = top5_profit.iloc[0:5][:]
#get item purchase count
pur_count_profit = pd.DataFrame(pur_data.groupby('Item ID')['Item ID'].count())

top5_profit = pd.merge(top5_profit, pur_count_profit, left_index = True, right_index = True, how = 'left')
top5_merge_profit = pd.merge(top5_profit, no_dup_items, left_index = True, right_on = 'Item ID', how = 'left')
top5_merge_profit = top5_merge_profit[['Item ID', 'Item Name', 'Item ID_x', 'Price_y','Price_x']]
top5_merge_profit.set_index(['Item ID'], inplace=True)
top5_merge_profit.rename(columns = {'Item ID_x': 'Purchase Count', 'Price_y': 'Item Price', 'Price_x': 'Total Purchase Value'}, inplace = True)
top5_merge_profit.style.format({'Item Price': '${:.2f}', 'Total Purchase Value': '${:.2f}'})

In [184]:
highest_priced = no_dup_items.sort_values('Price', ascending = False)
highest_priced[['Item ID', 'Item Name', 'Price']].head(18)

     Item ID                                 Item Name  Price
657       32                                   Orenmir   4.95
670      177  Winterthorn, Defender of Shifting Worlds   4.89
716      103                            Singed Scalpel   4.87
336      173                       Stormfury Longsword   4.83
419       42                           The Decapitator   4.82
436      131                                      Fury   4.82
398       96               Blood-Forged Skeletal Spine   4.77
455      137            Aetherius, Boon of the Blessed   4.75
686       46                   Hopeless Ebon Dualblade   4.75
743      134                           Undead Crusader   4.67
549      135                   Warped Diamond Crusader   4.66
737      101                              Final Critic   4.62
613      153                           Mercenary Sabre   4.57
567      181                             Reaper's Toll   4.56
421      150                                 Deathraze   4.54
300       99      Expiration, Warscythe Of Lost Worlds   4.53
411        7              Thorn, Satchel of Dark Souls   4.51
741      145                      Fiery Glass Crusader   4.45